name: Changelog

on:
  workflow_dispatch:

jobs:
  update:
    name: Update Changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update CHANGELOG
        run: echo "Changelog updated"
